server:
  servlet:
    context-path: /rabc #url的前缀
    
spring:
  profiles:
    active: dev
  #数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://locoalhost:3306/rabc
    username: root
    password: root
  #模版引擎
  thymeleaf:
    prefix: classpath:/templates/ #默认是这个
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #热部署
  devtools:
    restart:
      additional-paths: src/main/java #设置重启的目录，添加那个目录的文件需要重启
      enabled: true #热部署生效
      exclude: static/** , public/** , WEB-INF/** # 修改后不需要重启的文件
 

